apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-api
  namespace: sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sandbox
  name: sandbox-api
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "update", "list", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-api
  namespace: sandbox
subjects:
  - kind: ServiceAccount
    name: sandbox-api
    namespace: sandbox
roleRef:
  kind: Role
  name: sandbox-api
  apiGroup: rbac.authorization.k8s.io